const newQuote = () => {
let randomNumber = Math.floor(Math.random() * (quotes.length))
document.getElementById('quote').innerHTML = quotes[randomNumber]}

const quotes = [
    ["It'd be great if a car just ploughed into the lot of them, twisted broken bones.", 
    "Season 1, Episode 1 - Warring Factions"],
    ["Oh what, so Mister fucking ocean colour pants don't get it? Well, quelle fucking surprise.",
    "Season 1, Episode 1 - Warring Factions"],
    ["Pint of Guinness, please. No logo on the foam.",
    "Season 1, Episode 1 - Warring Factions"],
    ["Mark, you know I don't just bang anyone, yeah? I'm not some kind of next-door fuck jar.",
    "Season 1, Episode 1 - Warring Factions"],
    ["It'd be great if a car just ploughed into the lot of them, twisted broken bones.", 
    "Season 1, Episode 1 - Warring Factions"],
    ["Oh what, so Mister fucking ocean colour pants don't get it? Well, quelle fucking surprise.",
    "Season 1, Episode 1 - Warring Factions"],
    ["Pint of Guinness, please. No logo on the foam.",
    "Season 1, Episode 1 - Warring Factions"],
    ["Mark, you know I don't just bang anyone, yeah? I'm not some kind of next-door fuck jar.",
    "Season 1, Episode 1 - Warring Factions"],
    ["Socks before or after trousers, but never socks before pants, that’s the rule. Makes a man look scary – like a chicken.",
    "Season 1, Episode 2 - The Interview"],
    ["Shit! Shit, sugar, fudge, piss, poopants, bollocks.", 
    "Season 1, Episode 2 - The Interview"],
    ["I've been initiated. I am a drug user! Fuck the police!", 
    "Season 1, Episode 3 - On The Pull"],
    ["Will you walk, like some stupid.. duck? Or will you drive, like Clarkson?", 
    "Season 1, Episode 4 - Mark Makes A Friend"],
    ["I've made a psycho call to the woman I love, I kicked a dog to death, and now I'm going to pepperspray an acquaintance. Something ... I mean, what's happened to me?", 
    "Season 1, Episode 5, Dream Job"],
    [" Yeah well Mr. Dalai Lama, I suppose you've got to be a suck-up if you haven't got your own country.", 
    "Season 1, Episode 6 - Funeral"],
    ["What I really need is a good, long look at another man's bollocks. But that's so fraught with potential problems.", 
    "Season 1, Episode 6 - Funeral"],
    ["Careful, there's man love and there's business love, and never the twain shall meet.", 
    "Season 2, Episode 1, Dance Class"],
    ["Yeah, you won't be so cocky Jeff, when I come into the office with a Kalashnikov and 200 rounds of ammunition. I'm probably exactly the kind of person who could end up doing something like that.", 
    "Season 2, Episode 1, Dance Class"],
    ["Maybe I should send her a bit of ear. Or a finger. Just to show I'm really serious.", 
    "Season 2, Episode 1 - Dance Class"],
    ["Who needs romance when you're doing it up the bum?", 
    "Season 2, Episode 1 - Dance Class"],
    ["If I want to act relaxed, it's going to take all my cunning, skill, and concentration", 
    "Season 2, Episode 1 - Dance Class"],
    ["God it's so easy being a freak. No wonder they're ten a penny. I should get extra marks for not feeling a fucking thing.", 
    "Season 2, Episode 1 - Dance Class"],
    ["I'm Louis Theroux. I'm Louis Theroux with his wry smile at the orgy.", 
    "Season 2, Episode 1 - Dance Class"],
    ["This is good. This is like watching a porno, except I can't see anything, I haven't got a hard-on, and I want to cry.", 
    "Season 2, Episode 1 - Dance Class"],
    ["We can't throw that all away just because I ... spy on you ... can we!?", 
    "Season 2, Episode 1 - Dance Class"],
    ["Remember that time we made you wank off Percy's dog for a fiver?", 
    "Season 2, Episode 2 - Jeremy Makes It"],
    ["I'll tell you what, that crack is really moreish.", 
    "Season 2, Episode 2 - Jeremy Makes It"],
    ["Useless...all useless. I wish they were all robots...I wish I were a robot...maybe I could punch through a wall...", 
    "Season 2, Episode 2 - Jeremy Makes It"],
    ["She probably has really nice kidneys. Yeah, I'd fuck those kidneys real good.", 
    "Season 2, Episode 3 - Local Hero"],
    ["The secret ingredient [waves hand] is crime.", 
    "Season 2, Episode 4 - University Challenge"],
    ["Stealing things just makes everything very cheap. Plus, you know how I feel about capitalism.", 
    "Season 2, Episode 4 - University Challenge"],
    ["The jaws of death are best avoided --that's common knowledge!", 
    "Season 2, Episode 4 - University Challenge"],
    ["I'm dangerously close to getting what I want. Feels a bit weird.", 
    "Season 2, Episode 4 - University Challenge"],
    ["At least I didn't have to watch her recoil at my scrotal scar.", 
    "Season 2, Episode 4 - University Challenge"],
    ["This is okay... this is just a moment that'll haunt me forever.", 
    "Season 2, Episode 4 - University Challenge"],
    ["If you can't have sex with the monkey, make friends with the organ-grinder.", 
    "Season 2, Episode 5 - The Man Show"],
    ["I have entered the abyss. I've bought a house in the abyss. I'm getting my post forwarded to the abyss.", 
    "Season 2, Episode 5 - The Man Show"],
    [" I've been turning this thing over and over in my head like a bloody horrible pancake.", 
    "Season 2, Episode 5 - The Man Show"],
    ["Brilliant, Mark. My mate and your woman have just gone off to fuck each other. What are we gonna do now? Go and make a tent in the living room and eat Dairylea? Is that what you want? Because that's what's gonna happen.", 
    "Season 2, Episode 5 - The Man Show"],
    ["Oh don't marry those gays, Nancy. Marry me!", 
    "Season 2, Episode 6 - Wedding"],
    ["I'm a natural! Maybe I should try it on someone better looking.", 
    "Season 2, Episode 6 - Wedding"],
    ["Great. The woman you love has been single for only a few seconds and you've already found her a nice new boyfriend. Nice job, Mr Fucking Stupid.", 
    "Season 2, Episode 6 - Wedding"],
    ["Brilliant. Probably looks like I was going to punch him, when actually I was going to use the Buddhist as a human shield.", 
    "Season 2, Episode 6 - Wedding"],
    ["Public humiliation. Welcome to my world, Jeff. Although personally I wouldn't have picked that dress to cry on.", 
    "Season 2, Episode 6 - Wedding"],
    ["Do me? Are they going to rape me? Or kill me? If they rape AND kill me, I hope they kill me first....I sort-of win...", 
    "Season 3, Episode 1 - Mugging"],
    ["People like Coldplay and voted for the Nazis. You can't trust people, Jeremy.", 
    "Season 3, Episode 2 - Sectioning"],
    ["Listen love, just a little tip alright? You're on the edge now and you need to pick the right way. One way's heaven, and the other... well... probably best not to think about that right now... but it's fuckin' 'orrible, yeah?", 
    "Season3, Episode 3 - Shrooming"],
    ["It's not like I'm going to rape him. I could rape him... I'm not going to rape him.", 
    "Season 3, Episode 3 - Shrooming"],
    ["No, that's what they want you to do. That's where society's headed. People shitting in bags and throwing it out the window at each other. Well, I'm not going to be the first. Not in my name!", 
    "Season 3, Episode 3 - Shrooming"],
    ["So this is my big evening, is it? Me, tripping my nuts off, watching you do endless pooing.", 
    "Season 3, Episode 3 - Shrooming"],
    ["Looking at porn is like lying to Parliament. It used to be wrong but now it's all a big laugh.", 
    "Season 3, Episode 4 - Sistering"],
    ["Great. Okay, so I've 'dumped' my sister. That's great. That feels good. I'm intrigued to see what I'm gonna do next. Maybe I'll ring up Grandad, and tell him I think he's a boring twat", 
    "Season 3, Episode 4 - Sistering"],
    ["Hey! Wow, I'm actually good at this. Maybe I'm a natural - yeah, I'm a jogger! Of course, there had to be a sport for me, I just never realised. Legs like two great steam locomotives, pumping away, I'm unstoppable - JESUS, is that a stitch? Fuck, I'm gonna be sick, I need to walk. Oh, I think I'm gonna puke, I'm literally going to die, ugh, what an idiotic boob I was back ten or eleven seconds ago.", 
    "Season 3, Episode 4 - Sistering"],
    ["Frosties are just Cornflakes for people who can't face reality.", 
    "Season 3, Episode 5 - Jurying"],
    ["Saying 'I Love You' is like firing first in a duel; if you miss, you're fucked!", 
    "Season 3, Episode 5 - Jurying"],
    ["Look Mark, I'm a musician, in case you'd forgotten. Yeah? I answer to a higher law. The law of if it feels good, do it.", 
    "Season 3, Episode 5 - Jurying"],
    ["Colonel Gaddafi could not lay down a bass hook, Mark. That should be clear even to you!", 
    "Season 3, Episode 5 - Jurying"],
    ["I'm in Twelve Angry Men. I'm the only one who's not angry. I'm horny. That's much nicer.", 
    "Season 3, Episode 5 - Jurying"],
    ["So, a candle stuck in a wine bottle apparently doesn't cut it anymore. Now for a special night you have to have Class-A drugs and... fisting.", 
    "Season 3, Episode 5 - Jurying"],
    ["Why won't that stupid bitch let me propose to her?", 
    "Season 3, Episode 6 - Quantocking"],
    ["I've got a monkey on my back the size of King Kong. I am being fucked by King Kong!", 
    "Season 3, Episode 6 - Quantocking"],
    ["I'm so tired. She's gonna have a hell of a job coaxing a hard-on out of me. But I bet she'll manage", 
    "Season 3, Episode 6 - Quantocking"],
    ["He can't hear... Can you, you big fox-hunting, badger baiting, tweed-shirt bumfuck homophobe?", 
    "Season 4, Episode 1 - Sophie's Parents"],
    ["Of course he's not allowed to shoot. He's Mark Chapman in the making and I'm very much a 21st century Lennon", 
    "Season 4, Episode 1 - Sophie's Parents"],
    ["It's OK, it's perfectly normal, this is the country. This is what farmers do. They go around shooting crows, and trespassers, and eventually, because of the EU, themselves.", 
    "Season 4, Episode 1 - Sophie's Parents"],
    ["Don't be alarmed, Mark, it's just Tai Chi. Take a seat and I'll just power through. Should take 45 minutes, I'm done in ten. Stick that up your dojo.", 
    "Season 4, Episode 2 - Conference"],
    ["I do sort of like it when he's rude to me. Hopefully that's more of a psychological defect, not a weird sexual thing", 
    "Season 4, Episode 2- Conference"],
    ["In business, Jeremy, you learn that every man has his price, and I judge yours to be... £530.", 
    "Season 4, Episode 4- Conference"],
    ["God! I only asked her to be a hooker. It's not like I wanted her to work in telesales.", 
    "Season 4, Episode 2 - Conference"],
    ["Being black isn't about the colour of your skin. It's about vibe, hanging out, kicking back, smoking a number. Fighting prejudice and negative stereotypes wherever you find them! Yeah? I'm down with all that! Is Johnson? I mean, what's Johnson done for black people lately?!", 
    "Season 4, Episode 2 - Conference"],
    ["I'm about to walk into a boardroom gang bang and get fucked by the biggest swinging dicks in corporate strategy.", 
    "Season 4, Episode 2 - Conference"],
    ["God, I'm running away! This is brilliant! Maybe I'll go to KFC and have a whole bargain bucket! Or join Al Qaeda!", 
    "Season 4, Episode 2 - Conference"],
    ["And you don't have to be a smack-head to wank off old geezers, but that probably helps too.", 
    "Season 4, Episode 4 - Handyman"],
    ["If it ain't broke, don't fix it. And even if it is broke, just ignore it and maybe it'll be sort of OK. Like the environment.", 
    "Season 4, Episode 4- Handyman"],
    ["Oh great, so I'll be spending £1 a minute to hear how shit I am at sex. Now that's value for money!", 
    "Season 4, Episode 5 - Holiday"],
    ["Oh my God! I've entered an interview situation and there's a hand near my cock. This is like that dream I had about Alan Sugar and the Badger.", 
    "Season 4, Episode 5 - Holiday"],
    ["God I am dying for a piss. I feel like someone's inflating a balloon full of urine inside me. And not in a good way.", 
    "Season 4, Episode 6 - Wedding"],
    [".. But it was old style paedoing, before it got such a bad name.", 
    "Season 5, Episode 2 - Spin War"],
    ["The Big Beat Manifesto goes 'Big Beats are the best, Get high all the time'.", 
    "Season 5, Episode 2 - Spin war"],
    ["Oh God, I'm getting very... Captain Corrigan if flying without a licence! Oh Jesus, it's too much, I'm going to blow my beans! I'm going to do a Chesil Beach!", 
    "Season 5, Episode 2 - Spin War"],
    ["I win because they all think I pissed myself, when they have no idea I came all in my pants!", 
    "Season 5, Episode 2 - Spin War"],
    ["Hmmm... women. There they are, walking around. And they've all got them. Under their clothes. Hiding there. But I know the secret. Vaginas.", 
    "Season 5, Episode 2 - Spin War"],
    ["Maybe that was actually good sex? Loosen up, Corrigan - that's what happens in the bedroom now: no old fashioned fumbling and kissing, a lesbian rapes you whilst you dream about your mother. It's edgy.", 
    "Season 5, Episode 4- Jeremy's Mummy"],
    ["A suitcase with wheels? Real men don't get the earth to carry their luggage for them, mate. They carry it themselves.", 
    "Season 5, Episode 5 - Jeremy's Manager"],
    ["Wow, I've got a date! I'm a real piece of shit! I bet those two things go hand-in-hand. I bet if I got into defrauding pensioners, the pussy would really start rolling in.", 
    "Season 5, Episode 5 - Jeremy's Manager"],
    ["Look at them all - the Christians. It's not fair. I could be that happy if I believed in a lot of rubbish.", 
    "Season 5, Episode 5 - Jeremy's Manager"],
    ["That's cheating! Anyone can please a woman if she tells you what to do. You're not allowed to ask, that's the whole point.", 
    "Season 5, Episode 5 - Jeremy's Manager"],
    ["Sperm is like lending someone less than a fiver. You can't really ask for it back.", 
    "Season 5, Episode 6 - Mark's Women"],
    ["I don't want to take another wank bullet. What, am I some kind of wank shield?!", 
    "Season 6, Episode 3 - Jeremy in Love"],
    ["It'd be like picking off bystanders with a sniper rifle: fun at first, but it would quickly become a depressing chore.", 
    "Season 6, Episode 4 - The Affair"],
    ["I've always got the Three 0h Walcott millions.", 
    "Season 8, Episode 1 - Jeremy Therapised"],
    ["Finally, the use of Jeremy and Hans becomes clear: they're my normality cloaks. Allowing me to slip into human society and wreak my evil doings / make friends and relax.", 
    "Season 8, Episode 3 - The Love Bunker"],
    ["This stag is one load of PG-rated, Disney-assed, Which magazine approved, child-proof, high vitamin fucking bullshit.", 
    "Season 9, Episode 1 - The William Morris Years"],
    ["Let's detox till we've got mega cocks.", 
    "Season 9, Episode 1 - The William Morris Years"],
    ["I'm the Wolf of Wall Street. Look out, Boots, I'm going to buy a hundred meal deals and eat them off a prossie in the nude.", 
    "Season 9, Episode 1 - The William Morris Years"],
    ["Got to get my dick out of the dog.", 
    "Season 9, Episode 1 - The William Morris Years"],
    ["To be honest, uh, I've never really got it about Jesus. I mean, apart from all the Christian stuff, what did Jesus actually do?", 
    "Season 9, Episode 3 - Threeism"],
    ["You know I'm not saying I like him, but at least Hitler did some paintings.", 
    "Season 9, Episode 3- Threeism"],
    ["It’s the journey of life. Radio 1, Radio 2, Classic FM, Heart, Magic, dead.", 
    "Season 9, Episode 5 - Kid Farm"],
    ]

  console.log(quotes)
